### ISSUE TITLE
Design Improvement: Move transfer syntax detection out of main parser code 

### ISSUE THREAD

**Issue by chafey** [neandrake/dicom-pipe#5]
Currently the parser code has logic to detect the transfer syntax embedded inside of it.  Since DICOM P10 supplies the transfer syntax as part of the P10 header, transfer syntax detection should only be needed for non standards conforming DICOM files.  Detecting the transfer syntax is a useful feature, but also encourages use of non standards compliant files.  Ideally a strictly standards conforming interface would be exposed (and encouraged) and non standard conforming interfaces (e.g. one that will auto detect transfer syntax) would be exposed separately.  Taking this approach would also simplify the core parsing logic since it should not have anything to do with transfer syntax detection

**Comment by neandrake** [comment]
To bypass transfer syntax detection it should be possible to use the `ParserBuilder` to set the starting state to be `FileMeta` instead of `DetectTransferSyntax`, which would be more aligned with the standard. However if looking to strictly follow the standard an additional flag would need to be set on the parser indicating to never detect transfer syntax, as the `iterate_file_meta()` method will jump back to `DetectTransferSyntax` after the file-meta section has been read but no transfer syntax was declared.

As for the code... `iterate_detect_state()` is a big chunk of code (though I did try to comment and describe the entire process). Aside from moving some of this into a separate file only to be called by the parser I'm not sure if there's a great way to reduce the amount of code there.

However I'm in favor of allowing the parser to be lenient by default, but have the writer be strict by default. The only use case I can see for having a parser not be lenient is only for making a tool to check conformity of a dicom file to the standard. Allowing to parse invalid dicom won't really encourage non-standard dicom but does enable reading of a lot of the existing dicom that's already out there.

**Comment by chafey** [comment]
I am suggesting that the code be modularized  to make it more flexible and easier to understand, debug, test, etc.  This can be done by:
1) Extracting the transfer syntax detection code into its own file and be self contained
2) Extract the P10 Header parsing code into its own file and be self contained.
3) The transfer syntax will be passed to the parser so it can just do its job
4) Add higher level entry points that use the above 3 pieces of code to do what is currently being done

**Comment by neandrake** [comment]
Okay that makes sense. I'm interested to see what that ends up looking like.

**Comment by chafey** [comment]
OK I'll take a shot at it!

**Comment by neandrake** [comment]
Split out the parsing logic into sub-modules in c49798d08e03631abd59fdc2bdf797aa8ef973cc.

Tests will be refactored/added later
